FROM python:3.11.7

WORKDIR /app

RUN pip install --upgrade pip && pip install poetry==1.7.1

COPY pyproject.toml .
COPY poetry.toml .
COPY poetry.lock .

RUN poetry config virtualenvs.create false
RUN poetry install --with=dev --no-root

COPY src ./src
COPY settings.toml .
COPY migrations ./migrations
COPY alembic.ini .
RUN mkdir "models"

COPY tests ./tests
