"""add detect hate speech res

Revision ID: 0002
Revises: 0001
Create Date: 2024-01-20 09:25:20.750307

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_prompt_run',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_configs', sa.JSON(), nullable=True),
    sa.Column('llm_outputs', sa.JSON(), nullable=True),
    sa.Column('start_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_run', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_llm_prompt_run_uuid'), 'llm_prompt_run', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_prompt_run_uuid'), table_name='llm_prompt_run')
    op.drop_table('llm_prompt_run')
    # ### end Alembic commands ###
